;
;  Test program to test various library routines.
;
	.INCLUDE /$COMMON.MAC/
	.INCLUDE /MACROS.MAC/
	.PSECT CODE,SAV,CON,GBL,I
	.TITLE TEST Program to test various libarary routines
	.IDENT	"X00.00"
	.ENABL GBL
;
	.SBTTL start - Entry point to print message
	text hello, <Macro-11 Test Program>
	text prompt, <CMD: >
	text dot, <.>
	string str, 80.
start::
	BIS #flglz+flgsgn, flgnum
	putsln #hello
;
	cvtfqb #cfnam+cfext+cfppn+cfdev, #outbuf
	putsln #outbuf
;
	strr50 #hello, R0
	r50str #str, R0
	putsln #str
;
cloop:	puts #prompt		; Ask for a string
	gets #str		; Get the string
	trim #str,ts=1,lz=1,ls=1	; Trim the string
	upcase #str
	sfindc #str, #32., R1
	substr #str, #cmd, #0, R1
;
;  Check for EXIT command
;
	streq #cmd, #cexit
	BNE 100$
	JMP done
100$:	substr #str, #rest, R1, #0
	trim #rest, ls=1
;
;  Check for OCTAL command
;
	streq #cmd, #coct
	BNE 101$
	JMP octal
;
;  Check for DEC command
;
101$:	streq #cmd, #cdec
	BNE 102$
	JMP deci
;
;  Check for HEX command
;
102$:	streq #cmd, #chex
	BNE 103$
	JMP hexi
;
;  Check for LIST command
;
103$:	streq #cmd #clist
	BNE 104$
	JMP list
;
;  Check for STACK command
104$:	streq #cmd, #cstack
	BNE 105$
	JMP estack
;
;  No recognized command given
;
105$:	cpstr #firstw, #outbuf
	appstr #cmd, #outbuf
	appstr #vbar, #outbuf
	putsln #outbuf
;
	cpstr #trest, #outbuf
	appstr #rest, #outbuf
	appstr #vbar, #outbuf
	putsln #outbuf
;
	strchr #str, #5, R0
	chrstr #temp, R0
	cpstr #msg2, #outbuf
	appstr #temp, #outbuf
	appstr #vbar, #outbuf
	putsln #outbuf
;
	upcase #str
	puts #msg2
	puts #str
	putsln #vbar		; Put the uppercase string
	locase #str
	puts #msg2
	puts #str
	putsln #vbar		; Put the lowercase string
;
	puts #msg4		; Print the string's max len
	strmax #str, R0
	putdec R0
	JSR PC, newline
	puts #msg5		; Print the string's actual len
	strlen #str, R0
	putdec R0
	JSR PC, newline
;
	JMP cloop
;
octal:	stroct #rest, R1
	JSR PC, putnm1
	JMP cloop
;
deci:	strdec #rest, R1
	JSR PC, putnm1
	JMP cloop
;
hexi:	strhex #rest, R1
	JSR PC, putnm1
	JMP cloop
;
estack:	MOV R0, -(SP)
	MOV SP, R0
	cpstr #tstack, #outbuf
	octstr #str, R0
	appstr #str, #outbuf
	putsln #outbuf
	MOV (SP)+, R0
	JMP cloop
;
	.SBTTL Loop - To print numbers
list:	BIC #flglz+flgsgn, flgnum
	cpstr #rest, #str
	sfindc #str, #32., R1
	substr #str, #cmd, #0, R1
	substr #str, #rest, R1, #0
	trim #cmd,ls=1
	trim #rest,ls=1
	strdec #cmd, R1
	strdec #rest, R0
;
1$:	JSR PC, putnm1
	INC R1
	SOB R0, 1$
	JMP cloop
;
done:	JMP exit
;	.EXIT
;
;  Prints a number in octal, decimal, or hex.  The number is
;  passed in R1.  This is done by building a string and then
;  printing it all at once.
;
	text sgnum, <  The signed number is >
	text unum,  <The unsigned number is >
	text oct, < Octal, >
	text dec, < Decimal, >
	text hex, < Hexidecimal.>
putnm1:	BIS #flgsgn, flgnum
	cpstr #sgnum, #outbuf
	octstr #temp, R1
	appstr #temp, #outbuf
	appstr #oct, #outbuf
	decstr #temp, R1
	appstr #temp, #outbuf
	appstr #dec, #outbuf
	hexstr #temp, R1
	appstr #temp, #outbuf
	appstr #hex, #outbuf
	putsln #outbuf
	TST R1
	BGE 1$
	BIC #flgsgn, flgnum
	cpstr #unum, #outbuf
	octstr #temp, R1
	appstr #temp, #outbuf
	appstr #oct, #outbuf
	decstr #temp, R1
	appstr #temp, #outbuf
	appstr #dec, #outbuf
	hexstr #temp, R1
	appstr #temp, #outbuf
	appstr #hex, #outbuf
	putsln #outbuf
1$:	RTS PC
;
	.SBTTL Data - Space for text messages and strings
	string outbuf, 80.
	string temp, 80.
	string cmd, 80.
	string rest, 80.
	text enttxt, <Enter text: >
	text msg2, <You entered: |>
	text vbar, <|>
	text msg4, <The string max len is: >
	text msg5, <The string length is:  >
	text firstw, <The first word |>
	text trest, <The rest is |>
	text tstack, <Current SP is >
	text cexit, <EXIT>
	text coct, <OCTAL>
	text cdec, <DEC>
	text chex, <HEX>
	text clist, <LIST>
	text cstack, <STACK>
	.END start
