;
;  Test program to test various library routines.
;
	.INCLUDE /$COMMON.MAC/
	.INCLUDE /MACROS.MAC/
	.PSECT CODE,SAV,CON,GBL
	.TITLE TEST Program to test various libarary routines
	.IDENT	"X00.00"
	.ENABL GBL
;
; Need to include macros.mac to define common macros used here.
;
	.SBTTL start - Entry point to print message
start::
	putsln #hello
	puts #enttxt		; Ask for a string
	gets #str		; Get the string
	trim #str,ts=1,lz=1,tz=1,ls=1	; Trim the string
	puts #msg2		; Print the string
	puts #str
	putsln #vbar
;
	upcase #str
	puts #msg2
	puts #str
	putsln #vbar
	locase #str
	puts #msg2
	puts #str
	putsln #vbar
;
	puts #msg4		; Print the string's max len
	strmax #str, R0
	putdec R0
	JSR PC, newline
	puts #msg5		; Print the string's actual len
	strlen #str, R0
	putdec R0
	JSR PC, newline
;
	puts #entnum
	gets #str
	stroct #str, R1
	JSR PC, putnum
;
	puts #entnum
	gets #str
	strdec #str, R1
	JSR PC, putnum
;
	puts #entnum
	gets #str
	strhex #str, R1
	JSR PC, putnum
;
	.SBTTL Loop - To print numbers
	MOV #20., R0
	MOV #-10., R1
;
l1:	JSR PC, putnum
	ADD #1, R1
	SOB R0, l1
;
	octstr #str, #173757
	puts #msg2b
	puts #str
	putsln #vbar
	octstr #short1, #173757
	puts #msg2c
	puts #short1
	putsln vbar
;
	decstr #str, #31415.
	puts #msg2b
	puts #str
	putsln #vbar
	decstr #short2, #31415.
	puts #msg2c
	puts #short2
	putsln #vbar
;
	hexstr #str, #7777
	puts #msg2b
	puts #str
	putsln #vbar
	hexstr #short3, #7777
	puts #msg2c
	puts #short3
	putsln #vbar
;
	JSR PC, newline
	putsln #hello
	JSR PC, newline
	substr #hello, #str, #6, #5
	putsln #str
	.EXIT
;
;  Prints a number in octal, decimal, or hex.  The number is
;  passed in R1
;
putnum:	puts #msg3
	putoct R1
	puts #oct
	putdec R1
	puts #dec
	puthex R1
	putsln #hex
	RTS PC

	.SBTTL Data - Space for text messages and strings
	.PSECT DATA,CON
	text hello, <Hello world, again!>
	string str, 80.
	string short1, 5
	string short2, 4
	string short3, 3
	text msg2c <The truncated number is |>
	text enttxt, <Enter text: >
	text msg2, <You entered: |>
	text vbar, <|>
	text msg2b, <The number is |>
	text msg3, <The number is >
	text msg4, <The string max len is: >
	text msg5, <The string length is:  >
	text entnum, <Enter a number: >
	text oct, < Octal, >
	text dec, < Decimal, >
	text hex, < Hexidecimal >
	.END start
